name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-gateway:
    name: Test Gateway Service
    uses: ./.github/workflows/test.yml
    with:
      service-name: gateway

  test-loyalty:
    name: Test Loyalty Service
    uses: ./.github/workflows/test.yml
    with:
      service-name: loyalty

  test-payment:
    name: Test Payment Service
    uses: ./.github/workflows/test.yml
    with:
      service-name: payment

  test-reservation:
    name: Test Reservation Service
    uses: ./.github/workflows/test.yml
    with:
      service-name: reservation
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2


      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v2
          SERVICE_NAME: loyalty
          PORT_NUMBER: 8050

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v