name: Test Service
on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run tests
        run: go test ./internal/services/${{ inputs.service-name }}/...